# config.py
# Auto-converted from INI configuration file

AIR_TEMPERATURE = {
    "table": "tblAirTempGauging",
    "site_sql_id": "G_ID",
    "column": "A_Value",
    "datetime": "A_TimeDate",
    "data": "A_Value",
    "corrected_data": "A_Value",
    "utc_offset": "A_UTCOffset",
    "est": "A_Est",
    "estimate": "A_Est",
    "lock": "A_Lock",
    "warning": "A_Warning",
    "auto_timestamp": "AutoDTStamp",
    "update_timestamp": "AutoDTStamp",
    "provisional": "A_Provisional",
    "daily_table": "tblAirTempDaily",
    "daily_datetime": "A_Date",
    "daily_mean": "A_Mean",
    "daily_max": "A_Max",
    "daily_min": "A_Min",
    "daily_record_count": "A_RecCount",
    "daily_estimate": "A_Estimate",
    "daily_lock": "A_Lock",
    "daily_warning": "A_Warning",
    "daily_auto_timestamp": "AutoDTStamp",
    "daily_provisional": "A_Provisional",
    "daily_id": "R_DailyRain_ID",
    "telemetry_file": "File_Name",
    "observation_type": 4,
}

PRECIPITATION = {
    "table": "tblRainGauging",
    "site_sql_id": "G_ID",
    "daily_table": "tblRainDaily",
    "datetime": "R_TimeDate",
    "daily_datetime": "R_Date",
    "column": "R_Value",
    "data": "R_Value",
    "corrected_data": "R_Value",
    "utc_offset": "R_UTCOffset",
    "est": "R_Est",
    "estimate": "R_Est",
    "lock": "R_Lock",
    "warning": "R_Warning",
    "auto_timestamp": "AutoDTStamp",
    "update_timestamp": "AutoDTStamp",
    "provisional": "Provisional",
    "snow": "R_Snow",
    "observation_type": 0,
    "daily_sum": "R_TotalRain",
    "daily_mean": "mean",
    "daily_max": "max",
    "daily_min": "min",
    "daily_record_count": "R_RecCount",
    "daily_estimate": "R_Estimate",
    "daily_lock": "R_Lock",
    "daily_snow": "R_Snow",
    "daily_warning": "R_Warning",
    "daily_auto_timestamp": "AutoDTStamp",
    "daily_provisional": "R_Provisional",
    "daily_id": "R_DailyRain_ID",
    "telemetry_file": "File_Name",
    "unit": "inches",
}

WATER_TEMPERATURE = {
    "table": "tblWaterTempGauging",
    "site_sql_id": "G_ID",
    "column": "W_ValueCorrected",
    "datetime": "W_TimeDate",
    "data": "W_Value",
    "corrected_data": "W_ValueCorrected",
    "utc_offset": "W_UTCOffset",
    "est": "W_Est",
    "estimate": "W_Est",
    "ice": "W_Ice",
    "depth": "W_Depth",
    "warning": "W_Warning",
    "non_detect": "W_NonDetect",
    "lock": "W_Lock",
    "auto_timestamp": "AutoDTStamp",
    "update_timestamp": "AutoDTStamp",
    "upload_timestamp": "AutoDTStamp",
    "provisional": "W_Provisional",
    "daily_table": "tblWaterTempDaily",
    "daily_datetime": "W_Date",
    "daily_mean": "W_Mean",
    "daily_max": "W_Max",
    "daily_min": "W_Min",
    "daily_record_count": "W_RecCount",
    "daily_estimate": "W_Estimate",
    "daily_lock": "W_Lock",
    "daily_ice": "W_Ice",
    "daily_depth": "W_Depth",
    "daily_warning": "W_Warning",
    "daily_auto_timestamp": "AutoDTStamp",
    "daily_provisional": "W_Provisional",
    "daily_id": "W_WaterTemp_ID",
    "telemetry_file": "File_Name",
    "observation_type": 3,
    "unit": "deg. C",
}

BAROMETER = {
    "table": "tblBarometerGauging",
    "site_sql_id": "G_ID",
    "column": "B_Value",
    "datetime": "B_TimeDate",
    "data": "B_Value",
    "corrected_data": "B_Value",
    "utc_offset": "B_UTCOffset",
    "est": "B_Est",
    "estimate": "B_Est",
    "lock": "B_Lock",
    "warning": "B_Warning",
    "auto_timestamp": "AutoDTStamp",
    "update_timestamp": "AutoDTStamp",
    "provisional": "B_Provisional",
    "daily_table": "tblBarometerDaily",
    "daily_datetime": "B_Date",
    "daily_mean": "B_Mean",
    "daily_max": "B_Max",
    "daily_min": "B_Min",
    "daily_record_count": "B_RecCount",
    "daily_estimate": "B_Estimate",
    "daily_lock": "B_Lock",
    "daily_warning": "B_Warning",
    "daily_auto_timestamp": "AutoDTStamp",
    "daily_provisional": "B_Provisional",
    "daily_id": "B_DailyBaro_ID",
    "telemetry_file": "File_Name",
    "observation_type": 12,
}

CONDUCTIVITY = {
    "table": "tblConductivityGauging",
    "site_sql_id": "G_ID",
    "column": "C_ValueCorrected",
    "datetime": "C_TimeDate",
    "data": "C_Value",
    "corrected_data": "C_ValueCorrected",
    "utc_offset": "C_UTCOffset",
    "est": "C_Est",
    "estimate": "C_Est",
    "lock": "C_Lock",
    "warning": "C_Warning",
    "non_detect": "C_NonDetect",
    "auto_timestamp": "AutoDTStamp",
    "update_timestamp": "AutoDTStamp",
    "provisional": "C_Provisional",
    "daily_table": "tblConductivityDaily",
    "daily_datetime": "C_Date",
    "daily_mean": "C_Mean",
    "daily_max": "C_Max",
    "daily_min": "C_Min",
    "daily_record_count": "C_RecCount",
    "daily_estimate": "C_Estimate",
    "daily_lock": "C_Lock",
    "daily_warning": "C_Warning",
    "daily_auto_timestamp": "AutoDTStamp",
    "daily_provisional": "C_Provisional",
    "daily_id": "C_DailyCond_ID",
    "telemetry_file": "File_Name",
    "observation_type": 6,
    "unit": "umhos/cm",
}

DISSOLVED_OXYGEN = {
    "table": "tblDOGauging",
    "site_sql_id": "G_ID",
    "datetime": "O_TimeDate",
    "column": "O_DO_Grams_Corrected",
    "data": "O_DO_Grams",
    "corrected_data": "O_DO_Grams_Corrected",
    "precent": "O_DO_Percent",
    "temperature": "O_DO_Temp",
    "utc_offset": "O_UTCOffset",
    "est": "O_Est",
    "estimate": "O_Est",
    "non_detect": "D_NonDetect",
    "lock": "O_Lock",
    "warning": "O_Warning",
    "auto_timestamp": "AutoDTStamp",
    "provisional": "O_Provisional",
    "daily_table": "tblDODaily",
    "daily_datetime": "O_Date",
    "daily_mean": "O_Mean_Gramps",
    "daily_mean_precent": "O_Mean_Precent",
    "daily_max": "O_Max_Grams",
    "daily_min": "O_Min_Grams",
    "daily_record_count": "O_RecCount",
    "daily_estimate": "O_Estimate",
    "daily_lock": "O_Lock",
    "daily_warning": "O_Warning",
    "daily_auto_timestamp": "AutoDTStamp",
    "daily_provisional": "O_Provisional",
    "daily_id": "O_DailyDO_ID",
    "telemetry_file": "File_Name",
    "observation_type": 5,
    "unit": "mg/L",
}

DISCHARGE = {
    "table": "tblDischargeGauging",
    "site_sql_id": "G_ID",
    "daily_table": "tblDischargeDaily",
    "datetime": "D_TimeDate",
    "daily_datetime": "D_Date",
    "column": "D_Stage",
    "data": "D_Value",
    "corrected_data": "D_Stage",
    "discharge": "D_Discharge",
    "utc_offset": "D_UTCOffset",
    "est": "D_Est",
    "estimate": "D_Est",
    "lock": "D_Lock",
    "warning": "D_Warning",
    "non_detect": "D_NonDetect",
    "auto_timestamp": "AutoDTStamp",
    "update_timestamp": "AutoDTStamp",
    "provisional": "D_Provisional",
    "daily_mean": "D_MeanStage",
    "daily_max": "D_MaxStage",
    "daily_min": "D_MinStage",
    "daily_record_count": "D_RecCount",
    "discharge_mean": "D_MeanDis",
    "discharge_max": "D_MaxDis",
    "discharge_min": "D_MinDis",
    "daily_estimate": "D_Estimate",
    "daily_lock": "D_Lock",
    "daily_warning": "D_Warning",
    "daily_auto_timestamp": "AutoDTStamp",
    "daily_provisional": "D_Provisional",
    "daily_id": "D_DailyDis_ID",
    "telemetry_file": "File_Name",
    "observation_type": 2,
    "unit": "CFS",
}

ESCHERICHIA_COLI = {
    "unit": "CFU/100mL",
}

HUMIDITY = {
    "table": "tblRelativeHumidityGauging",
    "datetime": "H_TimeDate",
    "column": "H_Value",
}

LAKE_LEVEL = {
    "table": "tblLakeLevelGauging",
    "site_sql_id": "G_ID",
    "daily_table": "tblLakeLevelDaily",
    "datetime": "L_TimeDate",
    "daily_datetime": "L_Date",
    "column": "L_Level",
    "data": "L_Value",
    "corrected_data": "L_Level",
    "utc_offset": "L_UTCOffset",
    "est": "L_Est",
    "estimate": "L_Est",
    "lock": "L_Lock",
    "warning": "L_Warning",
    "non_detect": "L_NonDetect",
    "auto_timestamp": "AutoDTStamp",
    "update_timestamp": "AutoDTStamp",
    "provisional": "L_Provisional",
    "daily_mean": "L_MeanLevel",
    "daily_max": "L_MaxLevel",
    "daily_min": "L_MinLevel",
    "daily_record_count": "L_RecCount",
    "daily_estimate": "L_Estimate",
    "daily_lock": "L_Lock",
    "daily_warning": "L_Warning",
    "daily_auto_timestamp": "AutoDTStamp",
    "daily_provisional": "L_Provisional",
    "daily_id": "P_DailyLake_ID",
    "telemetry_file": "File_Name",
    "observation_type": 41,
    "unit": "wl_feet",
}

WATER_LEVEL = {
    "table": "tblLakeLevelGauging",
    "site_sql_id": "G_ID",
    "daily_table": "tblLakeLevelDaily",
    "datetime": "L_TimeDate",
    "daily_datetime": "L_Date",
    "column": "L_Level",
    "data": "L_Value",
    "corrected_data": "L_Level",
    "utc_offset": "L_UTCOffset",
    "est": "L_Est",
    "estimate": "L_Est",
    "lock": "L_Lock",
    "warning": "L_Warning",
    "non_detect": "L_NonDetect",
    "auto_timestamp": "AutoDTStamp",
    "update_timestamp": "AutoDTStamp",
    "provisional": "L_Provisional",
    "daily_mean": "L_MeanLevel",
    "daily_max": "L_MaxLevel",
    "daily_min": "L_MinLevel",
    "daily_record_count": "L_RecCount",
    "daily_estimate": "L_Estimate",
    "daily_lock": "L_Lock",
    "daily_warning": "L_Warning",
    "daily_auto_timestamp": "AutoDTStamp",
    "daily_provisional": "L_Provisional",
    "daily_id": "P_DailyLake_ID",
    "telemetry_file": "File_Name",
    "observation_type": 41,
    "unit": "wl_feet",
}

GROUNDWATER_LEVEL = {
    "table": "tblPiezometerGauging",
    "site_sql_id": "G_ID",
    "daily_table": "tblPiezometerDaily",
    "datetime": "P_TimeDate",
    "daily_datetime": "P_Date",
    "column": "P_Level",
    "data": "P_Value",
    "corrected_data": "P_Level",
    "utc_offset": "P_UTCOffset",
    "est": "P_Est",
    "estimate": "P_Est",
    "lock": "P_Lock",
    "warning": "P_Warning",
    "non_detect": "P_NonDetect",
    "auto_timestamp": "AutoDTStamp",
    "update_timestamp": "AutoDTStamp",
    "provisional": "P_Provisional",
    "amount_pumped": "P_GallonsPumped",
    "pump_state": "P_Pump_On",
    "observation_type": 0,
    "daily_mean": "P_MeanLevel",
    "daily_max": "P_MaxLevel",
    "daily_min": "P_MinLevel",
    "daily_record_count": "P_RecCount",
    "daily_estimate": "P_Estimate",
    "daily_lock": "P_Lock",
    "daily_warning": "P_Warning",
    "daily_auto_timestamp": "AutoDTStamp",
    "daily_provisional": "P_Provisional",
    "daily_amount_pumped": "P_GallonsPumped",
    "daily_pump_state": "P_Pummp_On",
    "daily_pump_hours": "P_PumpHours",
    "daily_id": "P_DailyPiezo_ID",
    "telemetry_file": "File_Name",
    "unit": "wl_feet",
}

PH = {
    "table": "tblpHGauging",
    "datetime": "pH_TimeDate",
    "column": "pH_ValueCorrected",
    "unit": "pH",
}

PIEZOMETER = {
    "table": "tblPiezometerGauging",
    "site_sql_id": "G_ID",
    "datetime": "P_TimeDate",
    "column": "P_Level",
    "data": "P_Value",
    "corrected_data": "P_Level",
    "utc_offset": "P_UTCOffset",
    "est": "P_Est",
    "estimate": "P_Est",
    "lock": "P_Lock",
    "warning": "P_Warning",
    "non_detect": "P_NonDetect",
    "auto_timestamp": "AutoDTStamp",
    "update_timestamp": "AutoDTStamp",
    "provisional": "P_Provisional",
    "gallons_pumped": "P_GallonsPumped",
    "pump_on": "P_Pump_On",
    "daily_id": "P_DailyPiezo_ID",
    "unit": "wl_feet",
}

RAIN = {
    "table": "tblRainGauging",
    "site_sql_id": "G_ID",
    "daily_table": "tblRainDaily",
    "datetime": "R_TimeDate",
    "daily_datetime": "R_Date",
    "column": "R_Value",
    "data": "R_Value",
    "corrected_data": "R_Value",
    "utc_offset": "R_UTCOffset",
    "est": "R_Est",
    "estimate": "R_Est",
    "lock": "R_Lock",
    "warning": "R_Warning",
    "auto_timestamp": "AutoDTStamp",
    "update_timestamp": "AutoDTStamp",
    "provisional": "Provisional",
    "snow": "R_Snow",
    "observation_type": 0,
    "daily_sum": "R_TotalRain",
    "daily_mean": "mean",
    "daily_max": "max",
    "daily_min": "min",
    "daily_record_count": "R_RecCount",
    "daily_estimate": "R_Estimate",
    "daily_lock": "R_Lock",
    "daily_snow": "R_Snow",
    "daily_warning": "R_Warning",
    "daily_auto_timestamp": "AutoDTStamp",
    "daily_provisional": "R_Provisional",
    "daily_id": "R_DailyRain_ID",
    "telemetry_file": "File_Name",
}

RAIN_TIPS = {
    "table": "tblRainGauging5minute",
    "site_sql_id": "G_ID",
    "datetime": "R_TimeDate",
    "column": "R_Value",
    "data": "R_Value",
    "corrected_data": "R_Value",
    "utc_offset": "R_UTCOffset",
    "est": "R_Est",
    "estimate": "R_Est",
    "lock": "R_Lock",
    "warning": "R_Warning",
    "auto_timestamp": "AutoDTStamp",
    "update_timestamp": "AutoDTStamp",
    "provisional": "Provisional",
    "snow": "R_Snow",
    "observation_type": 0,
    "telemetry_file": "File_Name_EventData",
}

TOTAL_ALKALINITY = {
    "unit": "mg CaCO3/L",
}

INORGANIC_NITROGEN = {
    "unit": "µg/L",
}

NITROGEN = {
    "unit": "ug/L",
}

ORGANIC_NITROGEN = {
    "unit": "µg/L",
}

TOTAL_NITROGEN = {
    "unit": "µg/L",
}

INORGANIC_PHOSPHORUS = {
    "unit": "µg/L",
}

PHOSPHORUS = {
    "unit": "ug/L",
}

ORGANIC_PHOSPHORUS = {
    "unit": "µg/L",
}

TOTAL_PHOSPHORUS = {
    "unit": "µg/L",
}

SOLAR_RAD = {
    "table": "tblSolarRadiationGauging",
    "datetime": "S_TimeDate",
    "column": "S_Value",
}

SOLAR_RADIATION = {
    "table": "tblSolarRadiationGauging",
    "site_sql_id": "G_ID",
    "daily_table": "tblSolarRadiationDaily",
    "datetime": "S_TimeDate",
    "daily_datetime": "S_Date",
    "column": "S_Value",
    "data": "S_Value",
    "corrected_data": "S_Value",
    "utc_offset": "S_UTCOffset",
    "est": "S_Est",
    "estimate": "S_Est",
    "lock": "S_Lock",
    "warning": "S_Warning",
    "auto_timestamp": "AutoDTStamp",
    "update_timestamp": "AutoDTStamp",
    "provisional": "Provisional",
    "observation_type": 34,
    "daily_mean": "S_Mean",
    "daily_max": "S_Max",
    "daily_min": "S_Min",
    "daily_record_count": "S_RecCount",
    "daily_estimate": "S_Estimate",
    "daily_lock": "S_Lock",
    "daily_warning": "S_Warning",
    "daily_auto_timestamp": "AutoDTStamp",
    "daily_provisional": "Provisional",
    "daily_id": "S_Rad_RecID",
    "telemetry_file": "File_Name",
}

WATER_TEMP = {
    "table": "tblWaterTempGauging",
    "datetime": "W_TimeDate",
    "column": "W_ValueCorrected",
}

TOTAL_SUSPENDED_SOLIDS = {
    "unit": "mg/L",
}

TURBIDITY = {
    "table": "tblTurbidityGauging",
    "site_sql_id": "G_ID",
    "daily_table": "tblTurbidityDaily",
    "datetime": "T_TimeDate",
    "daily_datetime": "T_Date",
    "column": "T_ValueCorrected",
    "data": "T_Value",
    "corrected_data": "T_ValueCorrected",
    "utc_offset": "T_UTCOffset",
    "est": "T_Est",
    "estimate": "T_Est",
    "lock": "T_Lock",
    "warning": "T_Warning",
    "auto_timestamp": "AutoDTStamp",
    "provisional": "Provisional",
    "observation_type": 0,
    "daily_mean": "T_Mean",
    "daily_max": "T_Max",
    "daily_min": "T_Min",
    "daily_record_count": "T_RecCount",
    "daily_estimate": "T_Estimate",
    "daily_lock": "T_Lock",
    "daily_warning": "T_Warning",
    "daily_auto_timestamp": "AutoDTStamp",
    "daily_provisional": "Provisional",
    "daily_id": "T_DailyTurb_ID",
    "telemetry_file": "File_Name",
    "unit": "NTU",
}

WIND = {
    "table": "tblWindSpeedGauging",
    "site_sql_id": "G_ID",
    "daily_table": "tblWindSpeedDaily",
    "datetime": "Wi_TimeDate",
    "daily_datetime": "Wi_Date",
    "column": "Wi_Value",
    "direction": "Wi_Direction",
    "data": "Wi_Value",
    "corrected_data": "Wi_Direction",
    "utc_offset": "Wi_UTCOffset",
    "est": "Wi_Estimate",
    "estimate": "Wi_Estimate",
    "lock": "Wi_Lock",
    "warning": "Wi_Warning",
    "auto_timestamp": "AutoDTStamp",
    "provisional": "Wi_Provisional",
    "observation_type": 35,
    "daily_mean_speed": "Wi_AveWindSpeed",
    "daily_max_speed": "Wi_MaxWindSpeed",
    "daily_min_speed": "Wi_MinWindSpeed",
    "daily_mean_direction": "Wi_AveWindDirection",
    "daily_max_direction": "Wi_MaxWindDirection",
    "daily_min_direction": "Wi_MinWindDirection",
    "daily_record_count": "Wi_RecCount",
    "daily_estimate": "Wi_Estimate",
    "daily_lock": "Wi_Lock",
    "daily_warning": "T_Warning",
    "daily_auto_timestamp": "AutoDTStamp",
    "daily_provisional": "Provisional",
    "daily_provisional_2": "Wi_Provisional",
    "telemetry_file": "File_Name",
}

SITE_IDENTIFICATION = {
    "site": "SITE_CODE",
    "site_sql_id": "G_ID",
    "table": "tblGaugeLLID",
    "latitude": "LAT",
    "longitude": "LON",
}

BATTERY = {
    "table": "tblBatteryVoltages",
    "site_sql_id": "G_ID",
    "datetime": "Voltage_Date",
    "column": "Voltage",
    "data": "Voltage",
    "corrected_data": "Voltage",
    "telemetry_file": "File_Name",
}


OBSERVATION = {
    "observation_table": "tblFieldVisitInfo",
    "observation_value_table": "tblFieldData",
    "observation_id": "FieldVisit_ID",
    "site_sql_id": "G_ID",
    "datetime": "Date_Time",
    "observation_number": "Measurement_Number",
    "observation_stage": "Stage_Feet",
    "observation_type": "Parameter",
    "observation_value": "Parameter_Value",
}

EDUCATION = {
    "college": "IIITA",
    "branch": "IT",
}

FAVORITES = {
    "sports": "VolleyBall",
    "books": "Historical Books",
}